Fix Object.groupBy callback arg
`Object.groupBy` takes as an argument a callback to return the
grouping keys.

Fixes the following error introduced in #2792:

```
TypeError: synonymId is not a function
    at Function.groupBy (<anonymous>)
    at default (file:///Users/lpsinger/src/gcn.nasa.gov/sandbox-search.js:13:40)
    at async getData (file:///Users/lpsinger/src/gcn.nasa.gov/node_modules/@nasa-gcn/architect-plugin-search/index.js:318:16)
    at async populate (file:///Users/lpsinger/src/gcn.nasa.gov/node_modules/@nasa-gcn/architect-plugin-search/index.js:327:16)
    at async start (file:///Users/lpsinger/src/gcn.nasa.gov/node_modules/@nasa-gcn/architect-plugin-search/index.js:628:5)
    at async runPlugins (/Users/lpsinger/src/gcn.nasa.gov/node_modules/@architect/sandbox/src/sandbox/plugins/index.js:25:9)
```